#!/bin/bash
echo BB-UART1 > /sys/devices/bone_capemgr.*/slots
echo BB-UART2 > /sys/devices/bone_capemgr.*/slots
echo BB-UART4 > /sys/devices/bone_capemgr.*/slots

echo STIV-GPIO > /sys/devices/bone_capemgr.*/slots
echo 49 > /sys/class/gpio/export
echo 115 > /sys/class/gpio/export
echo 60 > /sys/class/gpio/export
echo 48 > /sys/class/gpio/export
echo 50 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio115/direction
echo "out" > /sys/class/gpio/gpio49/direction
echo "out" > /sys/class/gpio/gpio60/direction
echo "in" > /sys/class/gpio/gpio48/direction
echo "out" > /sys/class/gpio/gpio50/direction

mkdir /mnt/ramdisk
mount -t tmpfs -o size=4m tmpfs /mnt/ramdisk
touch /mnt/ramdisk/sensorstable.html
echo "No data available or service is not running" > /mnt/ramdisk/sensorstable.html
touch /mnt/ramdisk/livedatatable.html
echo "No data available or service is not running" > /mnt/ramdisk/livedatatable.html
touch /mnt/ramdisk/settings.html
echo "No settings data available or service is not running" > /mnt/ramdisk/settings.html
touch /mnt/ramdisk/version.html
echo "No version data available or service is not running" > /mnt/ramdisk/version.html
